import {server} from '../config/index'
import BlogList from '@/components/BlogList'
import { Blog } from '@/types/index'
import Head from 'next/head'
import blog from './blog/[id]'

interface Props {
  blogs: Blog[]
}

const Home: React.FC<Props> = ({ blogs }) => {

  

  return (
    <div>
      <Head>
        <title>This is a title</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <BlogList blogs={blogs} />
    </div>
  )
}

// export const getStaticProps = async () => {
//   const res = await fetch(`https://localhost:3000/api/articles`)
//   const articles = await res.json()

//   return {
//     props: {
//       articles
//     }
//   } 
// }


export default Home

export const getStaticProps = async () => {
  const res = await fetch(`https://jsonplaceholder.typicode.com/posts?_limit=6`)
  const blogs = await res.json()

  return {
    props: {
      blogs
    }
  }
}

